### ISSUE TITLE
Matrix4::LookAt is incorrect

### ISSUE THREAD

**Issue by benjones** [mosra/magnum#127] opened 2015-12-10 03:41 UTC
To reproduce, spin a camera by setting the target to (0,0,0) and the eye position to `(r*cos(t), 5, r*sin(t))`.  It's pretty obvious that there's a bug in Matrix4::lookAt from that test.

I'm pretty sure the issue is that you're not transforming the eye before you put it into the last column of the matrix

This code (not pretty, but seems to be correct) fixes that issue by creating the homogeneousEye vector.

```
inline Matrix4 fixedLookAt(Vector3 eye, Vector3 target, Vector3 up){

  Vector3 forward = target - eye;
  forward = forward.normalized();

  up = up.normalized();

  Vector3 side = cross(forward,up).normalized();
  Vector3 fixedUp = cross(side, forward).normalized();

  Vector3 homogeneousEye(
      dot(-side, eye),
      dot(-fixedUp,eye),
      dot(forward, eye)
    );
  Matrix4 ret;
  //row 1 = side
  ret[0][0] = side[0];
  ret[1][0] = side[1];
  ret[2][0] = side[2];
  ret[3][0] = homogeneousEye[0];
  //row 2 = fixedUp
  ret[0][1] = fixedUp[0];
  ret[1][1] = fixedUp[1];
  ret[2][1] = fixedUp[2];
  ret[3][1] = homogeneousEye[1];
  //row 3 = backward
  ret[0][2] = -forward[0];
  ret[1][2] = -forward[1];
  ret[2][2] = -forward[2];
  ret[3][2] = homogeneousEye[2];
  //row 4 = identity
  ret[0][3] = 0;
  ret[1][3] = 0;
  ret[2][3] = 0;
  ret[3][3] = 1;

  return ret;

  }
```

**Comment by mosra** [comment] 2015-12-10 09:55
Hello, thanks a lot for the bugreport!

Something feels fishy to me -- you are setting the side/up/forward vectors as rows and not as columns, also the normalization seems to be done more times than strictly necessary. I'm not the author of the original code so first I need to investigate what is the expected behavior.

@wivlaro could you please look at this if you get some time? I'm not sure what was your use case and which approach is correct :)

**Comment by benjones** [comment] 2015-12-10 16:57
I'm pretty sure it's supposed to be across rows (see here: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/gluLookAt.3.html) 
Also, the glTranslate after glMulMatrix(M) is doing the same thing as my "homogeneous eye" bit.  

Almost certainly the number of normalizations can be cut down, and there's probably a better way to initialize the matrix, but hopefully it's a useful starting point.

Thanks

**Comment by mosra** [comment] 2015-12-17 20:48
Sorry about the silence, I'll look into this over the weekend, hopefully, when I have more than a few minutes of uninterrupted free time.

**Comment by decltype-auto** [comment] 2016-10-08 18:34
I think @benjones has a point here.

The matrix [es]V[ws]¹ to be yielded transforms the components of a vector v[ws]¹, given in world coordinates, to eye space.

v[es] = [es]V[ws] * v[ws] {I}

That [es]V[ws] matrix can be decomposed into 

[es]V[ws] = [es]T[rs] * [rs]R[ws], {II}

thus {I} can be decomposed into 

v[rs] =  [es]R[rs] * v[ws]
v[es] = [es]T[rs] * v[rs]

It's easy to read off the transformation part T of [the Magnum view matrix](https://github.com/mosra/magnum/blob/master/src/Magnum/Math/Matrix4.h#L679), that is the eyes translation matrix with reference to the world frame. 

T = [ws]T[ts]

But to get [es]T[rs] from this we would need

[es]T[rs] =   [rs]R[ws] T^-1  [ws]R[rs],

thus [es]V[ws] would be  

[es]V[ws] = [rs]R[ws] T^-1  [ws]R[rs] [rs]R[ws] = [rs]R[ws] T^-1.

> you are setting the side/up/forward vectors as rows and not as columns,

the left upper 3x3 of that [es]V[ws] is simply the inverse, thus because of the orthogonality of rotations simply the transpose, of the eye's column-wise aligned local triad, thus the triad is aligned row-wise in that [es]V[ws] and the inverse eye translation vector, contracted with those triad members as @benjones demonstrated,makes the rightmost column.

To validate that - [glm](http://glm.g-truc.net/0.9.8/index.html)  [has](https://github.com/g-truc/glm/blob/master/glm/gtc/matrix_transform.inl#L520) (also for FORTRAN memory layout)

```
template <typename T, precision P>
	GLM_FUNC_QUALIFIER tmat4x4<T, P> lookAtRH
	(
		tvec3<T, P> const & eye,
		tvec3<T, P> const & center,
		tvec3<T, P> const & up
	)
	{
		tvec3<T, P> const f(normalize(center - eye));
		tvec3<T, P> const s(normalize(cross(f, up)));
		tvec3<T, P> const u(cross(s, f));

		tmat4x4<T, P> Result(1);
		Result[0][0] = s.x;
		Result[1][0] = s.y;
		Result[2][0] = s.z;
		Result[0][1] = u.x;
		Result[1][1] = u.y;
		Result[2][1] = u.z;
		Result[0][2] =-f.x;
		Result[1][2] =-f.y;
		Result[2][2] =-f.z;
		Result[3][0] =-dot(s, eye);
		Result[3][1] =-dot(u, eye);
		Result[3][2] = dot(f, eye);
		return Result;
	}
```




¹ [ws] := components with reference to world space 
  [es] := components with reference to eyes space 
  [rs] := components with reference to a view with same trimming as the defined view, but located at world origin,
  [ts] := components with reference to a view with world axes-aligned trimming, but located at eye point 

 [x]M[y] := matrix that transform components from y to x space.

**Comment by mosra** [comment] 2016-10-15 13:27
Thanks for the input, @decltype-auto! 

I managed to go through your equations but I have a feeling that some of the letters don't match, especially in the 

> v[rs] = [es]R[rs] * v[ws]

part.

Anyway, whatever, now, thanks to your detailed explanation, I see that the core of the problem here is that the current implementation of `lookAt()` transforms the observer relative to the world, while your, benjones' and GLM implementation transforms the world relative to the observer, so the two implementations are basically an inverse of each other.

To verify that, I extended my test case like this:

```cpp
void Matrix4Test::lookAt() {
    Vector3 translation{5.3f, -8.9f, -10.0f};
    Vector3 target{19.0f, 29.3f, 0.0f};
    Matrix4 a = Matrix4::lookAt(translation, target, Vector3::xAxis());

    /* It's just a translation and rotation */
    CORRADE_VERIFY(a.isRigidTransformation());

    /* The matrix should translate to the position */
    CORRADE_COMPARE(a.translation(), translation);

    /* Forward vector should point in direction of the target */
    CORRADE_COMPARE(dot(-a.backward(), (target - translation).normalized()), 1.0f);

    /* Up vector should be in the same direction as X axis */
    CORRADE_VERIFY(dot(Vector3::xAxis(), a.up()) > 0.0f);

    ...
```

All those checks pass for the current implementation of `lookAt()` and also are in line with my expectations how such a transformation should behave. If I replace the current implementation of `lookAt()` with one of the above, the tests pass if I invert the generated matrix back:

```cpp
Matrix4 a = Matrix4::lookAt(translation, target, Vector3::xAxis()).inverted();
```

In my opinion the `lookAt()` should be usable not only for transforming the world relative to the camera but for general transformation of objects in the scene -- and that's where I see the inverted behavior problematic. Moreover, if you for example check the `shadows` example, there the function is used for transforming [both the camera object and the light object](https://github.com/mosra/magnum-examples/pull/24/files#diff-9721888c54bd69cbf2e6317508dd969eR138). The camera matrix inversion is done behind the scenes by the SceneGraph library and in order to use the proposed `lookAt()` implementation one would need to invert the result back each time, which doesn't feel very intuitive.

What I propose is updating the `lookAt()` documentation to mention the behavior of the function and suggest optional inverse, if someone's use case needs it. Would that be okay?

**Comment by decltype-auto** [comment] 2016-10-15 16:12
> I have a feeling that some of the letters don't match, especially in the
>     v[rs] = [es]R[rs] * v[ws]
> part.

That remark is valid, but that was plainly a typo of mine, that should be
v[rs] = [rs]R[ws] * v[ws]
of course. (fixed that above)

---

Generally - just take a y-up cam at (1,1,1)[ws] looking at world origin and let's look at the view matrix one get's for that.

``` c++
#include <iostream>
#include <iterator>
#define GLM_FORCE_CXX14
#define GLM_FORCE_RADIANS 
#include <glm/gtc/matrix_transform.hpp>
#include <Magnum/Math/Matrix4.h>

using real = float;

constexpr real EYE[] = {1.f, 1.f, 1.f};
constexpr real CENTER[] = {0.f, 0.f, 0.f};
constexpr real UP[] = {0.f, 1.f, 0.f};


template<class T, bool flag = true> struct traits;

template<> 
struct traits<glm::detail::tmat4x4<real, glm::lowp>> 
{
    using vec3 = glm::detail::tvec3<real, glm::lowp>;
    using vec4 = glm::detail::tvec4<real, glm::lowp>;
    
    static glm::detail::tmat4x4<real, glm::lowp> 
    lookAt (const vec3& eye, const vec3& center, const vec3& up) 
    {
        return glm::lookAt(eye, center, up); 
    };
}; // template<> struct traits<Magnum::Math::Matrix4<real>, false> 


template<> 
struct traits<Magnum::Math::Matrix4<real>, false> 
{
    using vec3 = Magnum::Math::Vector3<real>;
    using vec4 = Magnum::Math::Vector4<real>;
    
    static Magnum::Math::Matrix4<real> 
    lookAt (const vec3& eye, const vec3& center, const vec3& up)
    {
        return Magnum::Math::Matrix4<real>::lookAt(eye, center, up); 
    };
}; // template<> struct traits<Magnum::Math::Matrix4<real>, false> 


/////////////////////////////////////////////////////////////////////////////// 
// @benjones (https://github.com/benjones)
// https://github.com/mosra/magnum/issues/127
///////////////////////////////////////////////////////////////////////////////
namespace issue127{
    using Matrix4 = Magnum::Math::Matrix4<real>;
    using Vector3 = Magnum::Math::Vector3<real>;
    
    Matrix4 fixedLookAt(Vector3 eye, Vector3 target, Vector3 up) {

        Vector3 forward = target - eye;
        forward = forward.normalized();

        up = up.normalized();

        Vector3 side = cross(forward,up).normalized();
        Vector3 fixedUp = cross(side, forward).normalized();

        Vector3 homogeneousEye(
            dot(-side, eye),
            dot(-fixedUp,eye),
            dot(forward, eye)
            );
        Matrix4 ret;
        //row 1 = side
        ret[0][0] = side[0];
        ret[1][0] = side[1];
        ret[2][0] = side[2];
        ret[3][0] = homogeneousEye[0];
        //row 2 = fixedUp
        ret[0][1] = fixedUp[0];
        ret[1][1] = fixedUp[1];
        ret[2][1] = fixedUp[2];
        ret[3][1] = homogeneousEye[1];
        //row 3 = backward
        ret[0][2] = -forward[0];
        ret[1][2] = -forward[1];
        ret[2][2] = -forward[2];
        ret[3][2] = homogeneousEye[2];
        //row 4 = identity
        ret[0][3] = 0;
        ret[1][3] = 0;
        ret[2][3] = 0;
        ret[3][3] = 1;

        return ret;

    } // Matrix4 fixedLookAt(Vector3 eye, Vector3 target, Vector3 up)
    
} // namespace issue127


template<> 
struct traits<Magnum::Math::Matrix4<real>, true> 
{
    using vec3 = Magnum::Math::Vector3<real>;
    using vec4 = Magnum::Math::Vector4<real>;
    
    static Magnum::Math::Matrix4<real> 
    lookAt (const vec3& eye, const vec3& center, const vec3& up)
    {
        return issue127::fixedLookAt(eye, center, up); 
    };
}; //template<> struct traits<Magnum::Math::Matrix4<real>, true> 



template<typename M, bool flag> void test() {
    using vec3 = typename traits<M, flag>::vec3;
    using vec4 = typename traits<M, flag>::vec4;
    
    vec3 eye(EYE[0], EYE[1], EYE[2]);
    vec3 center(CENTER[0], CENTER[1], CENTER[2]);
    vec3 up{UP[0], UP[1], UP[2]};

    auto V = traits<M, flag>::lookAt(eye, center, up); 
    auto res = V * vec4(center, 1.0);

    std::cout << "maps world origin to:\t( ";
    std::copy(reinterpret_cast<real*>(&res), 
              (reinterpret_cast<real*>(&res)) + 3, 
              std::ostream_iterator<real>(std::cout, " "));
    std::cout << ")^T.\n";
} // template<typename M, bool flag> void test() 


int main() {
    std::cout << "glm lookAt    ";
    test<glm::detail::tmat4x4<real, glm::lowp>, true>(); 
    std::cout << "Magnum lookAt ";
    test<Magnum::Math::Matrix4<real>, false>();
    std::cout << "fixedLookAt   ";
    test<Magnum::Math::Matrix4<real>, true>(); 
        
    return 0;
}

```

World origin would have to be transformed to (0, 0,  -sqrt(3))^T for that cam. glm and @benjones '   code above do, but Magnum's current `lookAt()` doesn't:

Output:
```
glm lookAt    maps world origin to:	( 0 0 -1.73205 )^T.
Magnum lookAt maps world origin to:	( 1 1 1 )^T.
fixedLookAt   maps world origin to:	( 0 0 -1.73205 )^T.

```

**Comment by mosra** [comment] 2016-10-15 17:30
But that's *exactly* what I'm talking about above, if you invert the result, it gives the same value as GLM and benjones. In short:

```cpp
Debug() << Matrix4::lookAt(Vector3{1.0f}, {}, Vector3::yAxis()).transformPoint({});
Debug() << Matrix4::lookAt(Vector3{1.0f}, {}, Vector3::yAxis()).inverted().transformPoint({});
```

Prints out:
```cpp
Vector(1, 1, 1)
Vector(0, 0, -1.73205)
```

**Comment by decltype-auto** [comment] 2016-10-16 13:44
> `Matrix4::lookAt(Vector3{1.0f}, {}, Vector3::yAxis()).inverted()`
> vector(0, 0, -1.73205)

That proves that Magnum's `lookAt` doesn't yield a matrix for an oriented "eye" at eyepoint looking at a target.

It yields a matrix for a target "looking" at eyepoint, which is not just counter-intuitive, and differs from the colloquial notion of "lookAt"  but also also expensive because that unconstrained inversion by Cramer's rule is an expensive thing. 

And when you really need point "looking" at cam or light in a BSDF, it's anyway done in the shader because you'd need this on a per-vertex basis for the BSDF.

**Comment by mosra** [comment] 2016-10-19 09:37
> It yields a matrix for a target "looking" at eyepoint, which is not just counter-intuitive

I don't know. What's counter-intuitive to someone might be intuitive to someone else -- personally I don't see why `lookAt()` should behave in any other way than positioning an object to look at some different object. That also nicely fits into the current scene graph API, while I can't see any use for transforming a world that it is oriented in some way around the origin -- unless you want to drop all scene graph notions about treating the camera also as an object.

> and differs from the colloquial notion of "lookAt"

Magnum also doesn't use colloquial notion of "model-view" matrix, the "colloquial" GLM library or the well-known GLEW extension loader. I did some things differently because I saw more value in having it different than to repeat design decisions and potential mistakes of past implementors.

> but also also expensive because that unconstrained inversion by Cramer's rule is an expensive thing

OH COME ON, seriously? I tried to be *concise* in that snippet in order to prove a point, *not* to implement the most optimized technically correct solution. So I used the shortest method name. Of course this is inefficient and one should definitely use [Matrix4::invertedRigid()](http://mosra.cz/blog/magnum-doc/classMagnum_1_1Math_1_1Matrix4.html#abeb1abab1ff39721909c3d0f9ee27500) instead.

I clarified the documentation of `lookAt()` in 5fcdd48808fb2540e5ba1dd1a11c342ccd5926dd so the behavior should now be clear. Closing as resolved.

**Closed by mosra** 2016-10-19 09:37 UTC
