### ISSUE TITLE
flextGLInit null pointer dereference

### ISSUE THREAD

**Issue by thehans** [mosra/magnum#535] opened 2021-09-22 01:42 UTC
In the event that [eglQueryString](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglQueryString.xhtml) fails, the program crashes due to `strcmp` on `NULL`
> NULL is returned on failure.

The exception occurs here:
https://github.com/mosra/magnum/blob/b79bc1821902e9fd91700f0edc517b090809e19c/src/MagnumExternal/OpenGL/GL/flextGLPlatform.cpp#L52

**Comment by mosra** [comment] 2021-09-22 08:35
Uh oh, I was quite sure I did the check on most places, such as https://github.com/mosra/magnum/blob/b79bc1821902e9fd91700f0edc517b090809e19c/src/Magnum/Platform/Sdl2Application.cpp#L561

but missed this one. Fixing, thanks!

**Comment by mosra** [comment] 2021-09-22 11:44
Should be fixed with d09e91cac8469387feb3dc0aea515d2ad1213f84, the [StringView](https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1BasicStringView.html) class handles construction from a null pointer gracefully. 

Since I don't have any easy way to reproduce this, would be great if you could confirm it indeed fixes the problem. Thank you! :)

**Closed by mosra** 2021-09-22 11:44 UTC
