### ISSUE TITLE
Emscripten 3.1.21+ crashes EmscriptenApplication: "AsciiToString is not defined"

### ISSUE THREAD

**Issue by lacyyy** [mosra/magnum#619] opened 2023-05-03 00:48 UTC
I'm trying to get code from the ImGui Emscripten example to work, I'm compiling on Windows.
The app throws an error upon calling `Magnum::ImGuiIntegration::Context::updateApplicationCursor()`. Commenting out that call prevents that, but the cursor appearance obviously no longer changes.

![image](https://user-images.githubusercontent.com/91405033/235813040-2f32324e-add1-40b9-8f60-378a62575d06.png)

It works flawlessly when compiled on Emscripten 3.1.20 .
Looking at [Emscripten's changelogs](https://github.com/emscripten-core/emscripten/blob/6a546c283980a161f17076628d82824c96bb4a36/ChangeLog.md#3121---09092022), version 3.1.21 deprecated a few runtime functions, including `AsciiToString`.

**Comment by Squareys** [comment] 2023-05-27 19:44
There is `UTF8ToString` that can probably be used instead.

**Comment by mosra** [comment] 2023-09-03 16:26
This is fixed as of 25ebe436f1984c3992a9d24b138ede33f5683d2d. I'm currently testing with 3.1.44 and finding _tons_ of regressions in Emscripten itself, but this particular feature works now.

**Comment by mosra** [comment] 2023-09-03 22:34
Turns out that the `UTF8ToString`, `_malloc` etc. isn't guaranteed to be included either. For a lack of easier options I'm going to fix this with an accompanying JS library that directly specifies its runtime dependencies.

**Comment by mosra** [comment] 2023-09-04 21:16
A better solution is implemented in c3422cdd6ba520ab6eeeeb6d4719c03837fb7d99. This should also survive Emscripten versions 3.1.35+, which make `UTF8ToString` optional as well.

**Closed by mosra** 2023-09-04 21:16 UTC
Labels: changelog mention added
