### ISSUE TITLE
Segfault on draw using intel integrated Graphical controler

### ISSUE THREAD

**Issue by nerrvuss-ED** [mosra/magnum#172] opened 2016-09-08 12:31 UTC
Hello, It seems there is a problem using magnum with some Intel graphical chipset. (we have this exact error occurring on two laptop with intel integrated graphic controller). 
The program worked on other computer and laptop so we thought of a driver related problem.

It segfault after the initialization of magnum and the loading of assets (and it may be on the first draw call).
Could you tell me if it is a problem with magnum or if i am screwed because it came from the driver ^^?

Here the backtrace of gdb, don't mind the GrisReveur namespace it is our game engine :) 

VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

Renderer: Mesa DRI Intel(R) Haswell Mobile  by Intel Open Source Technology Center
OpenGL version: 3.0 Mesa 12.0.1
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_EXT_texture_filter_anisotropic
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
Render space init done.
[…]
Thread 10 "bootstrap" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea8d5700 (LWP 5410)]
0x00007ffff318e793 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
0  0x00007ffff318e793 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
1  0x00007fffe3ad1ccf in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
2  0x00007fffe3ad2751 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
3  0x00007fffe3ad2856 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
4  0x00007fffe3aea3f1 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
5  0x00007fffe3ad0d64 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
6  0x00007fffe38af833 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
7  0x00007ffff5cee2b2 in Magnum::Mesh::drawInternal(int, int, int, unsigned int, long, int, int) () from /usr/lib/libMagnum.so
8  0x00007ffff5cee1bf in Magnum::Mesh::draw(Magnum::AbstractShaderProgram&) () from /usr/lib/libMagnum.so
9  0x0000000000651566 in GrisReveur::MagnumSpriteDisplayable<GrisReveur::Tile<Map<World<OSSDreamCortex<GrisReveur::Brain<OSSBody, tlp::quote<GrisReveur::cortex::MagnumVideoCortex>, tlp::quote<GrisReveur::cortex::MagnumSensoryCortex>, tlp::quote<OSSDreamCortex> > > > > > >::draw (this=0x9bcbf0, transformationMatrix=..., camera=...)
    at […]gr-bootstrap/include/GrisReveur/include/GrisReveur/dreams/renders/MagnumSpriteDisplayable.hpp:216
10 0x00007ffff5421c07 in Magnum::SceneGraph::Camera<2u, float>::draw(Magnum::SceneGraph::FeatureGroup<2u, Magnum::SceneGraph::Drawable<2u, float>, float>&) () from /usr/lib/libMagnumSceneGraph.so

**Comment by mosra** [comment] 2016-09-08 16:18
Hmm. Crash deep inside a driver, that's not good...

It would be very helpful to see at which point in `Mesh::drawInternal()` it called the driver. Can you rebuild Magnum as `Debug` and paste a backtrace with line numbers?

Could you try running the app through [apitrace](https://apitrace.github.io/) and upload the trace file somewhere so I can go through it? I had some crashes related to not having buffer size set up correctly, but if you say that it worked elsewhere, this would be a problem with the particular set of GL features/extensions used on this machines.

Can you send me a log of Magnum initialization on machines where it worked so I can compare which extensions were used and which not?

**Comment by nerrvuss-ED** [comment] 2016-09-09 10:55
here the output of gdb with magnum compiled in debug (i cut the ugly tests output of the engine) :
http://pasteall.org/78691

here the link to the apitrace trace
https://framadrop.org/r/GdPZVM7qRa#Jx/pYGXDMyBbx80lWK4KE090UJeQ9DliscbCO2RqiNY=

i tried to test it on another laptop but it was also an intel shipset using the /usr/lib/xorg/modules/dri/i965_dri.so and i had the exact same error so i'll retry after noon

**Comment by mosra** [comment] 2016-09-11 15:04
Thanks for the trace file. Funnily enough, replaying the trace file crashes also on my NVidia box so the bad/good news is that it is not a driver problem but rather a bug in Magnum.

The cause of the crash is that the VAO doesn't have any buffer bound and so the data pointers are interpreted as client memory locations and not buffer offsets, which then of course is causing crash deep in the driver.

Apparently the problem is that I misunderstood the effect of binding VAOs on buffer binding state -- the buffer was already bound before binding the VAO and so after binding the VAO it called `glVertexAttribPointer()` without binding the buffer again, expecting that the buffer stayed bound, which is somehow not the case.

I'll investigate further, look in the specs to verify the proper behavior, add a test case for this and fix the culprit.

**Comment by mosra** [comment] 2016-09-11 18:25
Okay, scrap everything I said before, sorry for confusion. The state tracking was implemented the right way (otherwise this bug would have appeared much much sooner, as 90% of all my code is written this way).

I could not reproduce with a simple test case so I went through differences between my trace file and yours and found the following:

![image](https://cloud.githubusercontent.com/assets/344828/18419491/85d969ac-785c-11e6-97c2-4fda15cbf84c.png)

From a high-level point of view it seems that you accidentally did something like this:

```cpp
Mesh mesh;
{
    Buffer buffer;
    buffer.setData(someData, Buffer::Usage::StaticDraw);
    mesh.addVertexBuffer(buffer, ...);

    // here `buffer` gets destroyed
}

...

mesh.draw(...);
```

The VAO is still referencing the buffer, but the buffer got destroyed, so the drivers somehow decide that the `glVertexAttribPointer()` now suddenly points to client memory and not memory of that buffer (seems weird, huh, but both Intel and NV do the same, so it is probably correct that way). That it miraculously worked on some other drivers might be caused by the driver doing some reference counting and thus not deleting the buffer while it was still referenced by the VAO. I don't know which way is more correct, maybe the specification doesn't cover this at all so every driver vendor decided differently.

So I'm closing this as "not a bug". I hope I pointed you to the right direction :)

**Closed by mosra** 2016-09-11 18:25 UTC
Labels: bug
