### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [mosra/magnum#266] opened 2018-07-29 12:24 UTC
Would you like to [replace any double quotes](https://github.com/mosra/magnum/blob/fec1a07b9be7d9e73c1ecd7207ef3a2a59102981/src/Magnum/Magnum.h#L34 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by kghose** [comment] 2018-07-29 13:33
@elfring is this causing problems because you are compiling Magnum directly with your code? Just asking because I use it as an installed library and it's not affected me and I'm curious about why.

**Comment by elfring** [comment] 2018-07-29 13:50
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by kghose** [comment] 2018-07-29 14:20
Sorry, I'm a newbie, I still don't follow. 
- Is this slowing down compile times? 
- Are you compiling Magnum directly into your program i.e. you have the source code as a subdirectory in your code and have integrated the make files? 
- Are you having name clashes because you have some file names with an identical path in your project?

**Comment by kghose** [comment] 2018-07-29 15:30
@elfring ah, thank you for the clarification. So it's not a particular issue you've run into right now. 

I'm not involved with the project, just a user, but my personal preference is how things have been done now, as a visual indicator of what I can expect to belong to the project itself (quotes) as opposed to system or installed libraries (angle brackets). This helps when I inspect the magnum code.

In my project I end up using angle brackets when I include magnum elements as that is an installed library.

**Comment by elfring** [comment] 2018-07-29 15:40
Do you care (for example) why [the boost class library](https://www.boost.org/ "Portable C++ source libraries") is using angle brackets in include statements for corresponding header files?

**Comment by mosra** [comment] 2018-07-29 16:35
Hi again, @elfring!  I'm having the following convention for `#include ""` vs `#include <>`:

- if the include is project-local (so *not* from system directories, but rather from the project tree), I'm using `#include ""`. [Example of including a corresponding header for a *.cpp file](https://github.com/mosra/corrade/blob/96cf67a005e2b21f1ed88388219dadc62932ec40/src/Corrade/Utility/Unicode.cpp#L26), [example of Corrade project-local include](https://github.com/mosra/corrade/blob/96cf67a005e2b21f1ed88388219dadc62932ec40/src/Corrade/Containers/ArrayView.h#L36), [example of Magnum project-local include](https://github.com/mosra/magnum/blob/master/src/Magnum/Math/Vector.h#L41), [example of Magnum Plugins project-local include](https://github.com/mosra/magnum-plugins/blob/4c0111e3ee3e8fbd63b1e37c1568fd6139c830fa/src/MagnumPlugins/OpenGexImporter/OpenGexImporter.cpp#L44)
- if the include is from the system ([example](https://github.com/mosra/magnum/blob/8343217e1da018da954b21c1931c3f5d5c0d2385/src/Magnum/Math/Vector.h#L32)), from an external dependency ([example](https://github.com/mosra/magnum-plugins/blob/4c0111e3ee3e8fbd63b1e37c1568fd6139c830fa/src/MagnumPlugins/PngImporter/PngImporter.cpp#L29)) or from a dependent project -- so for example Corrade includes in Magnum ([example](https://github.com/mosra/magnum/blob/8343217e1da018da954b21c1931c3f5d5c0d2385/src/Magnum/Math/Vector.h#L36)) or Magnum includes in Magnum Plugins ([example](https://github.com/mosra/magnum-plugins/blob/master/src/MagnumPlugins/PngImporter/PngImporter.cpp#L32)), then I'm using `#include <>`.

This convention is followed very consistently across all Magnum-related projects and helps me see, for example, when debugging something, if I need to patch something in the current project (which is easier) or outside some other (which takes time). Basically what @kghose said above (thank you, @kghose!).

I don't buy the performance concern you have, including a system header that's not needed has much bigger impact than this and unless you want to prove that with a reproducible benchmark, I'll take this as just a speculation. OTOH, for example using `#pragma once` (which I'm not doing yet) *next to* include guards *does have* measurable speed difference. Also, I wouldn't take boost as an example, *especially* in relation to comple times. *Really*? ;)

I see that you opened 88 similar issues in almost 50 other repositories just this month and since *unfortunately* I have much pressing things to work on than having a discussion on these topics, I'll close this one as "wontfix". I hope you can understand that and acknowledge the very detailed reasoning behing the current state I posted above.

**Closed by mosra** 2018-07-29 16:35 UTC

**Comment by elfring** [comment] 2018-07-29 16:57
* @kghose: :crystal_ball: How do you interpret the visual indication (as a software user) if you would notice that an include statement (in the installed header file) continues to use quotes for other files (hopefully from an installed software library)?
* @mosra: You are the maintainer of this software library (and others?). The evolving source files (together with headers) can be treated as “project-local” while they are stored in your own development repository. But I find that the situation is significantly changed after these files were published as an official production release.  Include statements in the officially released files should use angle brackets then, shouldn't they?

**Comment by mosra** [comment] 2018-07-29 17:03
Man, this discussion is over, really. I thought it was clear. I stated all the reasons above and I'm not going to pour over everything and change things if it won't result in *significant* performance or usability improvement.

I really don't want to be mean and block / lock / report you, so please let's act like adults and stop the conversation here.
