### ISSUE TITLE
Compiler Error when building magnum WITH_DEPRECATED=OFF

### ISSUE THREAD

**Issue by roig** [mosra/magnum#372] opened 2019-09-18 22:40 UTC
Hello Mosra,
Building Magnum using VS2017 (latest version):
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="C:/Sys" -DWITH_SDL2APPLICATION=ON -DBUILD_DEPRECATED=OFF -DWITH_ANYIMAGEIMPORTER=ON -WITH_TEXT=ON
cmake --build . --target install --config Debug -- /m
```

Gives this error:
```
Build FAILED.

       "C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\install.vcxproj" (default target) (1) ->
       "C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\src\Magnum\Text\MagnumText.vcxproj" (default target) (25) ->
       (Link target) ->
         DistanceFieldGlyphCache.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall Magnum::GL::AbstractTexture::~AbstractTexture(void)" (__imp_??1AbstractTexture@GL@Magnum@@QAE@XZ) referenced in function "public: __thiscall Magnum::GL::Texture<2>::~Texture<2>(void)" (??1?$Texture@$01@GL@Magnum@@QAE@XZ) [C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\src\Magnum\Text\MagnumText.vcxproj]
         GlyphCache.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall Magnum::GL::AbstractTexture::~AbstractTexture(void)" (__imp_??1AbstractTexture@GL@Magnum@@QAE@XZ) [C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\src\Magnum\Text\MagnumText.vcxproj]
         C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\src\Magnum\Text\Debug\MagnumText-d.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\Dani\dev\endavant-dependencies\magnum\build_debug\src\Magnum\Text\MagnumText.vcxproj]

    0 Warning(s)
    3 Error(s)
```

**Comment by mosra** [comment] 2019-09-19 18:39
Sorry, being totally under pressure right now and it's unlikely I will be able to get to this until Monday. Is it okay for you to go with `BUILD_DEPRECATED` enabled until this is solved? This is probably related to 06aac867ae9240854e1bf0ea6c59c4c2afbb2c32 that changed this recently, but I have no idea why would it still think the destructor is public.

Is this happening with a totally fresh build dir as well?

**Comment by mosra** [comment] 2019-10-08 20:32
Closing as being caused by an inconsistent build state.

**Closed by mosra** 2019-10-08 20:32 UTC
Labels: no action needed

**Comment by roig** [comment] 2019-10-10 11:19
Hey, sorry Mosra, I was in my honeymoon so I was completely out. Close this. When I have free time, I will test if it is an inconsistent build state and if it is not, we can reopen this. Thank you!

**Comment by roig** [comment] 2019-10-20 10:19
After deleting old installation files compiled ok. Confirmed it was an inconsistent build state or something like that.
